### ISSUE TITLE
Add CI builds

### ISSUE THREAD

**Issue by jxm262** [aethant/vanilla-css#14]
assuming to use TravisCI

**Comment by Seikho** [comment]
I'm not sure if TravisCI can handle SnarkErrors

**Comment by neutraltone** [comment]
hmm are we hand writing each test via CL prior to each release?

**Comment by Seikho** [comment]
See #15

**Comment by Seikho** [comment]
Need to configure `travis-ci.org` to build our project

**Comment by jxm262** [comment]
looks like Alex added this.  Will contact him for the badge

**Comment by jxm262** [comment]
@Seikho  @aethant  thanks :+1:
