### ISSUE TITLE
Create a build

### ISSUE THREAD

**Issue by kevrom** [aethant/vanilla-css#3]
Currently the vanilla CSS is unminified.  I really feel like you should add a build step so people can include that. Every byte counts, y'know.

**Comment by aethant** [comment]
:+1:

**Comment by Seikho** [comment]
This is a must. Our current build pipeline is very disjointed and hard to replicate.

**Comment by JDDoesDev** [comment]
Will the mobile app work on android?

**Comment by neutraltone** [comment]
Hmm, could I suggest an artisan approach? I propose we use vanilla minification and do this by hand.

**Comment by neutraltone** [comment]
I've assigned @aethant for the task of hand minification. He's quite meticulous so he'll be perfect for the job.

**Comment by JDDoesDev** [comment]
I think we should term the minified vanilla css Minilla CSS to avoid confusion.

**Comment by neutraltone** [comment]
Woah woah, renegade's need not apply.

**Comment by aethant** [comment]
Im on a bit of holiday. Back to you @neutraltone

**Comment by adriansalgadoa** [comment]
I disagree with this. The code should be as-is with no modifications what so ever so we can easily showcase how easy and beautiful it is to user our framework. :no_entry_sign:

**Comment by Seikho** [comment]
Implemented in #8

**Comment by jxm262** [comment]
I think we can take a middle of the road approach between a complex build and @LasagnaAndroid 's suggestion.  My vote is to make a build file with the following (perhaps use make or some other build tool)  

```

```

(yes you read that right, absolutely blank so the users can fill it in)
